@server = localhost:3000
@api_path = api
@api_version = 1
@url = http://{{server}}/{{api_path}}/v{{api_version}}

# collects all events should return all events.
###############################################
GET {{url}}/events
###############################################

// test1
GET {{url}}/events/69ae86d2c1bcbd6dfad9e16e
###############################################

// Fail to fetch
GET {{url}}/events/6991dce013ded751d7a90d2
###############################################

// Post event
POST {{url}}/events
Content-Type: application/json

{
	"title": "Match and Mingle",
	"description": "An evening of quick rounds and great conversations.",
	"date": "2026-03-01T18:30:00.000Z",
	"location": "Blight Town",
	"maxSpots": 20
}
###############################################

// Fail to post event from lack of content
POST {{url}}/events
Content-Type: application/json

{
	"title": "",
	"description": "An evening of quick rounds and great conversations.",
	"date": "2026-03-01T18:30:00.000Z",
	"location": "Community Hall",
	"maxSpots": 40
}
###############################################

// Delete event
DELETE {{url}}/events/69932bbc083c3a2d89f3aa5b
###############################################

// Update event
PUT {{url}}/events/6991dce013ded751d7a90d2f
Content-Type: application/json

{
  "title": "Ändrat namn",
  "description": "updated desc.",
  "date": "2026-04-01T18:30:00.000Z",
  "location": "Community ändrat hall",
  "maxSpots": 60
}
###############################################

// Register for event
POST {{url}}/events/698ef39bc55f2bea2a95ae59/register
Content-Type: application/json
###############################################

// unregister for event
DELETE {{url}}/events/698ef39bc55f2bea2a95ae59/register
Content-Type: application/json
###############################################

# generate matches for round 1
GET {{url}}/events/69ae86d2c1bcbd6dfad9e16e/1/match
Content-Type: application/json
###############################################

# Generate matches for Round 2 of the event
GET {{url}}/events/69ae86d2c1bcbd6dfad9e16e/2/match
Content-Type: application/json
###############################################

# Generate matches for Round 3 of the event
GET {{url}}/events/69ae86d2c1bcbd6dfad9e16e/3/match
Content-Type: application/json
###############################################

# Save finalized matches for Round 1
POST {{url}}/events/69ae86d2c1bcbd6dfad9e16e/1/matches
Content-Type: application/json

{
  "matches": [
    {
      "man": "69939c73879f9f04d4e38186",
      "woman": "69939c73879f9f04d4e38194",
      "tableNumber": 1,
      "manSeat": "left",
      "womanSeat": "right"
    },
    {
      "man": "69939c73879f9f04d4e38188",
      "woman": "69939c73879f9f04d4e38191",
      "tableNumber": 2,
      "manSeat": "left",
      "womanSeat": "right"
    },
    {
      "man": "69939c73879f9f04d4e3818e",
      "woman": "69939c73879f9f04d4e38192",
      "tableNumber": 3,
      "manSeat": "left",
      "womanSeat": "right"
    },
    {
      "man": "69939c73879f9f04d4e38189",
      "woman": "69939c73879f9f04d4e38196",
      "tableNumber": 4,
      "manSeat": "left",
      "womanSeat": "right"
    },
    {
      "man": "69939c73879f9f04d4e3818a",
      "woman": "69939c73879f9f04d4e38190",
      "tableNumber": 5,
      "manSeat": "left",
      "womanSeat": "right"
    },
    {
      "man": "69939c73879f9f04d4e3818b",
      "woman": "69939c73879f9f04d4e38197",
      "tableNumber": 6,
      "manSeat": "left",
      "womanSeat": "right"
    },
    {
      "man": "69939c73879f9f04d4e3818c",
      "woman": "69939c73879f9f04d4e38195",
      "tableNumber": 7,
      "manSeat": "left",
      "womanSeat": "right"
    },
    {
      "man": "69939c73879f9f04d4e38187",
      "woman": "69939c73879f9f04d4e38198",
      "tableNumber": 8,
      "manSeat": "left",
      "womanSeat": "right"
    },
    {
      "man": "69939c73879f9f04d4e3818d",
      "woman": "69939c73879f9f04d4e3818f",
      "tableNumber": 9,
      "manSeat": "left",
      "womanSeat": "right"
    },
    {
      "man": "69939c73879f9f04d4e38185",
      "woman": "69939c73879f9f04d4e38193",
      "tableNumber": 10,
      "manSeat": "left",
      "womanSeat": "right"
    }
  ]
}
###############################################