@server = localhost:3000
@api_path = api
@api_version = 1
@url = http://{{server}}/{{api_path}}/v{{api_version}}

# collects all events should return all events.
###############################################
GET {{url}}/events
###############################################

// test1
GET {{url}}/events/6991dce013ded751d7a90d2f
###############################################

// Fail to fetch
GET {{url}}/events/6991dce013ded751d7a90d2
###############################################

// Post event
POST {{url}}/events
Content-Type: application/json

{
	"title": "Match and Mingle",
	"description": "An evening of quick rounds and great conversations.",
	"date": "2026-03-01T18:30:00.000Z",
	"location": "Blight Town",
	"maxSpots": 20
}
###############################################

// Fail to post event from lack of content
POST {{url}}/events
Content-Type: application/json

{
	"title": "",
	"description": "An evening of quick rounds and great conversations.",
	"date": "2026-03-01T18:30:00.000Z",
	"location": "Community Hall",
	"maxSpots": 40
}
###############################################

// Delete event
DELETE {{url}}/events/69932bbc083c3a2d89f3aa5b
###############################################
// Update event
###############################################

PUT {{url}}/events/6991dce013ded751d7a90d2f
Content-Type: application/json

{
  "title": "Ändrat namn",
  "description": "updated desc.",
  "date": "2026-04-01T18:30:00.000Z",
  "location": "Community ändrat hall",
  "maxSpots": 60
}
###############################################


###############################################

// Register for event
POST {{url}}/events/698ef39bc55f2bea2a95ae59/register
Content-Type: application/json

###############################################


###############################################

// unregister for event
DELETE {{url}}/events/698ef39bc55f2bea2a95ae59/register
Content-Type: application/json
###############################################

###############################################
# generate matches for round 1
GET {{url}}/events/69a5c588038b17e575f3c00b/1/match
Content-Type: application/json
###############################################

# Generate matches for Round 2 of the event
GET {{url}}/events/69a5c588038b17e575f3c00b/2/match
Content-Type: application/json
###############################################

# Generate matches for Round 3 of the event
GET {{url}}/events/69a5c588038b17e575f3c00b/3/match
Content-Type: application/json
###############################################
